@{
    Capabilities = @(
        'Print.Fax.Scan'
        'Language.Handwriting'
        'Browser.InternetExplorer'
        'MathRecognizer'
        'OneCoreUAP.OneSync'
        'OpenSSH.Client'
        'Microsoft.Windows.MSPaint'
        'Microsoft.Windows.PowerShell.ISE'
        'App.Support.QuickAssist'
        'Microsoft.Windows.SnippingTool'
        'Language.Speech'
        'Language.TextToSpeech'
        'App.StepsRecorder'
        'Media.WindowsMediaPlayer'
        'Microsoft.Windows.WordPad'
    )
}
